server:
  port: ${DB_PORT}
spring:
  dataSource:
    url: jdbc:postgresql://localhost:5432/${DB_URL}
    username: ${USER_NAME}
    password: ${USER_PASS}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO}
    show-sql: true
jwt:
  secret: ${SECRET_KEY}
